// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['firebaseWebAPIKEY']!,
    appId: '1:176028498006:web:561b978a770cbf5aede3f7',
    messagingSenderId: '176028498006',
    projectId: 'ignite-matchsticks-pam',
    authDomain: 'ignite-matchsticks-pam.firebaseapp.com',
    storageBucket: 'ignite-matchsticks-pam.appspot.com',
    measurementId: 'G-VM56FH4NXB',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['firebaseAndroidAPIKEY']!,
    appId: '1:176028498006:android:e000e83fdf48e5d9ede3f7',
    messagingSenderId: '176028498006',
    projectId: 'ignite-matchsticks-pam',
    storageBucket: 'ignite-matchsticks-pam.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['firebaseIOSAPIKEY']!,
    appId: '1:176028498006:ios:a52c742db2f8df3eede3f7',
    messagingSenderId: '176028498006',
    projectId: 'ignite-matchsticks-pam',
    storageBucket: 'ignite-matchsticks-pam.appspot.com',
    iosBundleId: 'com.example.flutterLearnings',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['firebaseMacOSAPIKEY']!,
    appId: '1:176028498006:ios:b3ade0110d6e3156ede3f7',
    messagingSenderId: '176028498006',
    projectId: 'ignite-matchsticks-pam',
    storageBucket: 'ignite-matchsticks-pam.appspot.com',
    iosBundleId: 'com.example.flutterLearnings.RunnerTests',
  );
}
